name: Flash Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flash:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug JFrog URL
        run: |
            echo "JF_URL=${{ vars.JF_URL }}"

      - name: Download firmware from JFrog artifactory
        run: |
            FW_PATH="${{ vars.FW_PATH }}"

            if [ -z "${FW_PATH}" ]; then
              echo "::error::FW_PATH is not set."
              exit 1
            fi

            jf rt dl \
              --spec ./.github/config/download_firmware_spec.json \
              --spec-vars "repo_path=${FW_PATH}"

            for fw in ControlBrd1_CM4.elf ControlBrd1_CM7.elf; do
              if [ ! -f "boards/firmwares/platform-control-board/$fw" ]; then
                echo "::error::$fw not found in Artifactory."
                exit 1
              fi
            done

      - name: Flash firmware to board
        run: ./scripts/flash_firmware.sh boards/firmwares/platform-control-board/ControlBrd1_CM7.elf boards/firmwares/platform-control-board/ControlBrd1_CM4.elf
