name: Flash Firmware

on:
  push:
    branches:
      - main

jobs:
  flash:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Flash firmware to board
        run: ./scripts/flash_firmware.sh boards/firmwares/platform-control-board/ControlBrd1_CM7.elf boards/firmwares/platform-control-board/ControlBrd1_CM4.elf
